Added `loop` construct to the grammar
tree-sitter/tree-sitter-ruby pull request #181
Opened 2021-07-07 13:42 UTC by typoon

Added the `loop` statement to the grammar together with tests for it. This solves part of the issue described in https://github.com/tree-sitter/tree-sitter-ruby/issues/180

Checklist:
- [X] All tests pass in CI.
- [X] There are sufficient tests for the new fix/feature.
- [X] Grammar rules have not been renamed unless absolutely necessary.
- [X] The conflicts section hasn't grown too much.
- [X] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

2021-07-07 14:07 UTC, aryx commented
lgtm

2021-07-07 14:51 UTC, maxbrunsfeld commented
Is loop not just an ordinary method in ruby?

2021-07-07 14:54 UTC, maxbrunsfeld requested changes
I believe that loop parsers correctly with the current grammar; loop is a method that takes a block.

If you think that it’s actually dedicated syntax in ruby, could you explain why?

2021-07-07 18:00 UTC, typoon commented
> I believe that loop parses correctly with the current grammar; loop is a method that takes a block.
> 
> If you think that it’s actually dedicated syntax in ruby, could you explain why?

You are right there. And thinking about it now, perhaps I am going about this in the wrong way, but there might be a different issue here then. Consider this piece of code:

```ruby
def example
  x = "hi"
  loop do
    x = "hello"
    y = "hey"
    break
  end

  puts x
  puts y
end
```

`x` is in the scope of the `example` function and `y` is in the scope of the `loop` function. The `puts y` line will thrown an exception because `y` does not exist there.

The thing is, when I stop the cursor on the `x` variable, all the instances of it in this function should be highlighted (the ones inside and outside the `loop` block) as its scope is for the whole function. The `y` variable on the other hand, shouldn't.

If we make the `loop` construct be interpreted as a control expression, then the `x` is treated as being in the scope of the function, but so does the `y`, which brings the inverse problem of what I was trying to solve.

I think I don't have a real solution here. Any ideas or suggestions on how to go about it?

2021-07-20 15:49 UTC, closed without merging

2021-07-20 15:50 UTC, typoon commented
It makes no sense to accept this PR as it was the wrong way of dealing with the problem. I will open an issue for the dealing with variable scopes.